### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by oliverkieslich** [firegento/firegento-pdf-paypalplus#1]
Hi,

we are running on Magento CE 1.9.2.
Iways_PayPalPlus is version 1.4.5
FireGento_Pdf is version 1.3.0
FireGento_PdfPayPalPlus is version 1.0.0

When I press the "print" button within an invouice, we get a HTTP ERROR 500. 
This line in the Observer.php seems to be the problem:

if ($paymentMethod != Iways_PayPalPlus_Model_Payment::METHOD_CODE) {

Wehen I change it to 

if ($paymentMethod != "iways_paypalplus_payment") { 

the error disappears. What´s going wrong?

One question: the module "adds the detailed PayPalPlus payment information on the FireGento PDF invoices". Where does this information come from? I ask because I need informations about another bank account on the  invoice BUT ONLY when the payment method is INVOICE (over PayPalPlus). 

Thank you

Oliver

**Comment by sprankhub** [comment]
Iways_PayPalPlus 1.4.5 is quite old. Please update to the latest version 1.8.3. The constant we use `Iways_PayPalPlus_Model_Payment::METHOD_CODE` has probably been introduced in later versions.

The information comes from the PayPalPlus extension. It is the same information you see when you open the order in the backend and look at the payment information.
