### ISSUE TITLE
Customweb Paypal Plus Extension

### ISSUE THREAD

**Issue by Grueff** [firegento/firegento-pdf-paypalplus#2]
After some bugs with the iways paypal plus extension, i had to buy the extension by customweb (sellxed).
But it seems that the payment datas arent included in firegento pdf.
In the magento stock pdf i can see the datas. I dont know how to integrate it in firegento too.
Is there any possibility?

**Comment by sprankhub** [comment]
Since it is a paid extension, we cannot really help here. This tiny extension should give you a good idea how it could be integrated in FireGento PDF. If you are looking for paid help, feel free to contact me privately.
